### ISSUE TITLE
sample cam

### ISSUE THREAD

**Issue by Palymer** [ThatUsernameAlreadyExist/TECKIN-TC100-Anyka-AK3918-camera-hacks#1]
I have about the same camera, just a different company. The chip inside is version 300 (instead of 200), your hack works and I can access the camera via browser, but the video stream does not work. Can you tell me in what direction to dig?

![Screenshot_1](https://github.com/ThatUsernameAlreadyExist/TECKIN-TC100-Anyka-AK3918-camera-hacks/assets/51864661/08bb646b-79a8-427d-9c9c-4da9cecb400e)
![Screenshot_2](https://github.com/ThatUsernameAlreadyExist/TECKIN-TC100-Anyka-AK3918-camera-hacks/assets/51864661/e8b18e35-8b60-4de6-96ed-60db7916cd4e)
![Screenshot_3](https://github.com/ThatUsernameAlreadyExist/TECKIN-TC100-Anyka-AK3918-camera-hacks/assets/51864661/f91675f1-05e5-4b99-ad5f-e04afbe0fae5)

**Comment by Palymer** [comment]
![image](https://github.com/ThatUsernameAlreadyExist/TECKIN-TC100-Anyka-AK3918-camera-hacks/assets/51864661/c40fa530-7fc7-41fa-ae98-c32df74ccdf4)
I tried to run it manually, it comes out that the configuration is a bit different and the configuration file doesn't fit. What to do? There is no way to fix anything inside the file system, only on the microsd card?

**Comment by Palymer** [comment]
![image](https://github.com/ThatUsernameAlreadyExist/TECKIN-TC100-Anyka-AK3918-camera-hacks/assets/51864661/cf460944-e5de-4a6d-914e-111fc2b3a27e)
I have corrected the configuration in /mnt/config/rtspserver.conf file

**Comment by ThatUsernameAlreadyExist** [comment]
Yes, your camera has a different sensor. But according to the logs, the rtsp server worked fine after the configuration was changed (at least the initialization was successful). Is it possible to connect to the rtsp stream after that?

**Comment by Palymer** [comment]
![image](https://github.com/ThatUsernameAlreadyExist/TECKIN-TC100-Anyka-AK3918-camera-hacks/assets/51864661/68c646c7-8021-41ee-9b74-33bdf28183b7)
yes, streaming works, just reduces the recording quality from 25 frames from 25 to 15, rtsp through vnc player works fine
