### ISSUE TITLE
Password required

### ISSUE THREAD

**Issue by BoBaSrEvEnGe** [ThatUsernameAlreadyExist/TECKIN-TC100-Anyka-AK3918-camera-hacks#10]
Hi, the hack seems to work. Thank you! However, I have a problem, the IP address of the camera is found. However, a password is required. Is there a general password?

**Comment by ThatUsernameAlreadyExist** [comment]
Try this: 
Default camera login/password: root/pass

**Comment by BoBaSrEvEnGe** [comment]
Thank you for the quick response. It works now. Thank you!
