### ISSUE TITLE
Work out of the box on GNCC T1PRO camera

### ISSUE THREAD

**Issue by antibill51** [ThatUsernameAlreadyExist/TECKIN-TC100-Anyka-AK3918-camera-hacks#3]
Just a little message to thank you for this excellent work.
It works perfectly on a GNCC T1PRO camera.

https://www.amazon.fr/gp/product/B09LQGMKVH/

I'm just having a little problem with the time zone. I had to use "UTC-1" instead of "UTC+1" to add 1 hour of offset.

**Comment by ThatUsernameAlreadyExist** [comment]
> I'm just having a little problem with the time zone. I had to use "UTC-1" instead of "UTC+1" to add 1 hour of offset.

This is normal (even though it looks weird). Linux (and the POSIX standard) uses the reverse sign when declaring a timezone. For simplicity, code sets the timezone according to this standard. 
Here is more information about it: https://unix.stackexchange.com/questions/104088/why-does-tz-utc-8-produce-dates-that-are-utc8
