### ISSUE TITLE
/mnt/bin/getimage 

### ISSUE THREAD

**Issue by dylanlanigansmith** [ThatUsernameAlreadyExist/TECKIN-TC100-Anyka-AK3918-camera-hacks#4]
Hey thanks for this, 
combined with the cross compiler on another repo I have been having a blast messing with the old tc100s I had laying around.. 

Just wondering if you could source/provide insight into the getimage program.. wondering if a full resolution snapshot is possible- I decompiled 'getiimage' briefly and doesn't seem like there are any parameters or resolution configs used inside the program. 

Thanks again, and appreciate any insight into getimage.

Dylan

**Comment by ThatUsernameAlreadyExist** [comment]
Hello,
getimage source code can be found here: https://github.com/ThatUsernameAlreadyExist/anyka-v4l2rtspserver/blob/main/libv4l2cpp/src/GetImage.cpp

But it is not needed to get full resolution snapshot, you just need to change rtsp-server config:
in **config\rtspserver.conf** file change 

    jpegstream=1
    
to

    jpegstream=0
    
and restart the rtsp-server 
(in ' jpegstream' param 0 is the high-resolution stream index, 1 is the low-resolution stream index)

**Comment by dylanlanigansmith** [comment]
Oh [I was using this](https://github.com/ricardojlrufino/anyka_v380ipcam_experiments/tree/master) for the CC/etc and tweaking stuff to work for the TC100/your image... and you've had it all along!!! Silly me for not looking, glad I haven't spent too much time doing work that it seems like you kindly already have! Thanks so much!

**Comment by dylanlanigansmith** [comment]
Works like a charm thanks again!
``jpegstream=0
